server:
  port: 8080
spring:
  main:
    web-application-type: reactive
  application:
    name: community
  datasource:
    url: jdbc:mysql://${mysql.host:localhost}:${mysql.port:3306}/testdb?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${mysql.username:root}
    password: ${mysql.password:root}
    type: com.alibaba.druid.pool.DruidDataSource
  data:
    mongodb:
      uri: mongodb://localhost/testdb